### ISSUE TITLE
Messages from the bot should be displayed as block

### ISSUE THREAD

**Issue by ghost** [jellz/sky#21]
The responses/messages that the bot makes should not be line-per-line basis instead use a discord block to prevent spam and message fragmentation.

Ex.
```javascript
new Discord.RichEmbed()
            .setDescription(message)
            .setColor(color)
            .setAuthor(title, thumbnailUrl)
        );
```

**Comment by jellz** [comment]
Is that your only example? Sky does not use any embeds. At all. Whatsoever.

**Comment by ghost** [comment]
Why so?

**Comment by jellz** [comment]
That's just its style - I don't know why haha, it's an embed-free bot

**Comment by ghost** [comment]
Wasn't aware of that lol
